/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.39
 * Generated at: 2024-03-05 15:59:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class adminViewReview_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/Users/Amulya/OneDrive/Documents/Desktop/online%20cloth%20store/test/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/577PROJECT/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098691290000L));
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1706721384505L));
    _jspx_dependants.put("/adminsession.jsp", Long.valueOf(1706721384507L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	int admin_id = (Integer) session.getAttribute("admin_id");
	String admin_name = (String) session.getAttribute("admin_name");
	response.setHeader("Cache-Control","no-cache");
	response.setHeader("Cache-Control","no-store");
	response.setHeader("Pragma","no-cache");
	response.setDateHeader ("Expires", 0);
	
	if(session.getAttribute("admin_id") == null){
		response.sendRedirect("adminLogin.jsp");
	}

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>All Review</title>\r\n");
      out.write("</head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://www.w3schools.com/w3css/4/w3.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Roboto\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Montserrat\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("<style>\r\n");
      out.write(".w3-sidebar a {font-family: \"Roboto\", sans-serif}\r\n");
      out.write("body,h1,h2,h3,h4,h5,h6,.w3-wide {font-family: \"Montserrat\", sans-serif;}\r\n");
      out.write("form {border: 3px solid #f1f1f1;}\r\n");
      out.write("\r\n");
      out.write("input[type=text], input[type=password] {\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  padding: 12px 20px;\r\n");
      out.write("  margin: 8px 0;\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  border: 1px solid #ccc;\r\n");
      out.write("  box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button {\r\n");
      out.write("  background-color: #4CAF50;\r\n");
      out.write("  color: white;\r\n");
      out.write("  padding: 14px 20px;\r\n");
      out.write("  margin: 8px 0;\r\n");
      out.write("  border: none;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button:hover {\r\n");
      out.write("  opacity: 0.8;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".cancelbtn {\r\n");
      out.write("  width: auto;\r\n");
      out.write("  padding: 10px 18px;\r\n");
      out.write("  background-color: #f44336;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".imgcontainer {\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  margin: 24px 0 12px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("img.avatar {\r\n");
      out.write("  width: 40%;\r\n");
      out.write("  border-radius: 50%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container {\r\n");
      out.write("  padding: 16px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("span.psw {\r\n");
      out.write("  float: right;\r\n");
      out.write("  padding-top: 16px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tablez{\r\n");
      out.write("  border-radius: 5px;\r\n");
      out.write("  background-color: #f2f2f2;\r\n");
      out.write("  padding: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("#tabel2{\r\n");
      out.write("  font-family: Arial, Helvetica, sans-serif;\r\n");
      out.write("  border-collapse: collapse;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#tabel2 td, #customers th {\r\n");
      out.write("  border: 1px solid #ddd;\r\n");
      out.write("  padding: 8px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#tabel2 tr:nth-child(even){background-color: #f2f2f2;}\r\n");
      out.write("\r\n");
      out.write("#tabel2 tr:hover {background-color: #ddd;}\r\n");
      out.write("\r\n");
      out.write("#tabel2 th {\r\n");
      out.write("  padding-top: 12px;\r\n");
      out.write("  padding-bottom: 12px;\r\n");
      out.write("  text-align: left;\r\n");
      out.write("  background-color: #4CAF50;\r\n");
      out.write("  color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<body class=\"w3-content\" style=\"max-width:1200px\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Sidebar/menu -->\r\n");
      out.write("<nav class=\"w3-sidebar w3-bar-block w3-white w3-collapse w3-top\" style=\"z-index:3;width:250px\" id=\"mySidebar\">\r\n");
      out.write("  <div class=\"w3-container w3-display-container w3-padding-16\">\r\n");
      out.write("    <i onclick=\"w3_close()\" class=\"fa fa-remove w3-hide-large w3-button w3-display-topright\"></i>\r\n");
      out.write("    <h3 class=\"w3-wide\"><b>Ketupat Sdn Bhd.</b></h3>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"w3-padding-64 w3-large w3-text-grey\" style=\"font-weight:bold\">\r\n");
      out.write("  \t<a href=\"home.jsp\" class=\"w3-bar-item w3-button\">Homepage</a> \r\n");
      out.write("\t<a href=\"viewAccount?action=viewaccount\" class=\"w3-bar-item w3-button\">View account</a>\r\n");
      out.write("\t<a href=\"ViewProductController\" class=\"w3-bar-item w3-button\">View product</a>\r\n");
      out.write("\t<a href=\"addProduct.jsp\" class=\"w3-bar-item w3-button\">Add product</a>\r\n");
      out.write(" \t<a href=\"adminCreateAccount.jsp\" class=\"w3-bar-item w3-button\">Create admin</a>\r\n");
      out.write("\t<a href=\"viewPaymentController\" class=\"w3-bar-item w3-button\">View Record</a>\r\n");
      out.write("\t<a href=\"viewReviewController\" class=\"w3-button w3-block w3-white w3-left-align\">View Review</a>\r\n");
      out.write("\t<a href=\"AdminLogoutController\" class=\"w3-bar-item w3-button\">Logout</a>\r\n");
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("   <!--\r\n");
      out.write("    <a onclick=\"myAccFunc()\" href=\"javascript:void(0)\" class=\"w3-button w3-block w3-white w3-left-align\" id=\"myBtn\">\r\n");
      out.write("      Jeans <i class=\"fa fa-caret-down\"></i>\r\n");
      out.write("    </a>\r\n");
      out.write("    <div id=\"demoAcc\" class=\"w3-bar-block w3-hide w3-padding-large w3-medium\">\r\n");
      out.write("      <a href=\"#\" class=\"w3-bar-item w3-button w3-light-grey\"><i class=\"fa fa-caret-right w3-margin-right\"></i>Skinny</a>\r\n");
      out.write("      <a href=\"#\" class=\"w3-bar-item w3-button\">Relaxed</a>\r\n");
      out.write("      <a href=\"#\" class=\"w3-bar-item w3-button\">Bootcut</a>\r\n");
      out.write("      <a href=\"#\" class=\"w3-bar-item w3-button\">Straight</a>\r\n");
      out.write("    </div>\r\n");
      out.write("    -->\r\n");
      out.write("\r\n");
      out.write("  <a href=\"#footer\" class=\"w3-bar-item w3-button w3-padding\">Contact</a> \r\n");
      out.write("  <a href=\"javascript:void(0)\" class=\"w3-bar-item w3-button w3-padding\" onclick=\"document.getElementById('newsletter').style.display='block'\">Newsletter</a> \r\n");
      out.write("  <a href=\"#footer\"  class=\"w3-bar-item w3-button w3-padding\">Subscribe</a>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<!-- Top menu on small screens -->\r\n");
      out.write("<header class=\"w3-bar w3-top w3-hide-large w3-black w3-xlarge\">\r\n");
      out.write("  <div class=\"w3-bar-item w3-padding-24 w3-wide\">Ketupat Sdn Bhd.</div>\r\n");
      out.write("  <a href=\"javascript:void(0)\" class=\"w3-bar-item w3-button w3-padding-24 w3-right\" onclick=\"w3_open()\"><i class=\"fa fa-bars\"></i></a>\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("<!-- Overlay effect when opening sidebar on small screens -->\r\n");
      out.write("<div class=\"w3-overlay w3-hide-large\" onclick=\"w3_close()\" style=\"cursor:pointer\" title=\"close side menu\" id=\"myOverlay\"></div>\r\n");
      out.write("\r\n");
      out.write("<!-- !PAGE CONTENT! -->\r\n");
      out.write("<div class=\"w3-main\" style=\"margin-left:250px\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Push down content on small screens -->\r\n");
      out.write("  <div class=\"w3-hide-large\" style=\"margin-top:83px\"></div>\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("  <!-- Jangan kacau atas  -------------------------------------------------------------------------->\r\n");
      out.write("  <!-- Jangan kacau atas  -------------------------------------------------------------------------->\r\n");
      out.write("  <!-- Jangan kacau atas  -------------------------------------------------------------------------->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!-- Top header ---------------------------------------------------------------------------------->\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("  <!-- Top header ---------------------------------------------------------------------------------->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!-- Image header -------------------------------------------------------------------------------->\r\n");
      out.write("  <div class=\"w3-display-container w3-container\">\r\n");
      out.write("    <img src=\"background.jpg\" alt=\"Jeans\" style=\"width:100%\">\r\n");
      out.write("    <div class=\"w3-display-topleft w3-text-white\" style=\"padding:24px 48px\">\r\n");
      out.write("      <h1 class=\"w3-jumbo w3-hide-small\">New arrivals</h1>\r\n");
      out.write("      <h1 class=\"w3-hide-large w3-hide-medium\">New arrivals</h1>\r\n");
      out.write("      <h1 class=\"w3-hide-small\">COLLECTION 2020</h1>\r\n");
      out.write("     \r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("   <!-- Image header -------------------------------------------------------------------------------->\r\n");
      out.write("\r\n");
      out.write("   <br>\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("\t<br>\r\n");
      out.write("\r\n");
      out.write("  <!-- Product grid \r\n");
      out.write("  <div class=\"w3-row w3-grayscale\">\r\n");
      out.write("    <div class=\"w3-col l3 s6\">\r\n");
      out.write("      <div class=\"w3-container\">\r\n");
      out.write("        <img src=\"/w3images/jeans1.jpg\" style=\"width:100%\">\r\n");
      out.write("        <p>Ripped Skinny Jeans<br><b>$24.99</b></p>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"w3-container\">\r\n");
      out.write("        <img src=\"/w3images/jeans2.jpg\" style=\"width:100%\">\r\n");
      out.write("        <p>Mega Ripped Jeans<br><b>$19.99</b></p>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"w3-col l3 s6\">\r\n");
      out.write("      <div class=\"w3-container\">\r\n");
      out.write("        <div class=\"w3-display-container\">\r\n");
      out.write("          <img src=\"/w3images/jeans2.jpg\" style=\"width:100%\">\r\n");
      out.write("          <span class=\"w3-tag w3-display-topleft\">New</span>\r\n");
      out.write("          <div class=\"w3-display-middle w3-display-hover\">\r\n");
      out.write("            <button class=\"w3-button w3-black\">Buy now <i class=\"fa fa-shopping-cart\"></i></button>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <p>Mega Ripped Jeans<br><b>$19.99</b></p>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"w3-container\">\r\n");
      out.write("        <img src=\"/w3images/jeans3.jpg\" style=\"width:100%\">\r\n");
      out.write("        <p>Washed Skinny Jeans<br><b>$20.50</b></p>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"w3-col l3 s6\">\r\n");
      out.write("      <div class=\"w3-container\">\r\n");
      out.write("        <img src=\"/w3images/jeans3.jpg\" style=\"width:100%\">\r\n");
      out.write("        <p>Washed Skinny Jeans<br><b>$20.50</b></p>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"w3-container\">\r\n");
      out.write("        <div class=\"w3-display-container\">\r\n");
      out.write("          <img src=\"/w3images/jeans4.jpg\" style=\"width:100%\">\r\n");
      out.write("          <span class=\"w3-tag w3-display-topleft\">Sale</span>\r\n");
      out.write("          <div class=\"w3-display-middle w3-display-hover\">\r\n");
      out.write("            <button class=\"w3-button w3-black\">Buy now <i class=\"fa fa-shopping-cart\"></i></button>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <p>Vintage Skinny Jeans<br><b class=\"w3-text-red\">$14.99</b></p>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"w3-col l3 s6\">\r\n");
      out.write("      <div class=\"w3-container\">\r\n");
      out.write("        <img src=\"/w3images/jeans4.jpg\" style=\"width:100%\">\r\n");
      out.write("        <p>Vintage Skinny Jeans<br><b>$14.99</b></p>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"w3-container\">\r\n");
      out.write("        <img src=\"/w3images/jeans1.jpg\" style=\"width:100%\">\r\n");
      out.write("        <p>Ripped Skinny Jeans<br><b>$24.99</b></p>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("  -->\r\n");
      out.write("\r\n");
      out.write("  <table id=\"tabel2\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th>Review ID</th>\r\n");
      out.write("\t\t\t<th>Product Name</th>\r\n");
      out.write("\t\t\t<th>Star Rating</th>\r\n");
      out.write("\t\t\t<th>Review</th>\r\n");
      out.write("\t\t\t<th>Payment Date</th>\r\n");
      out.write("\t\t\t<th>Customer Email</th>\r\n");
      out.write("\t\t\t<th>Action</th>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t</table>\r\n");
      out.write("\r\n");
      out.write("\t<br><br>\r\n");
      out.write("\r\n");
      out.write("  <!-- Jangan kacau atas  -------------------------------------------------------------------------->\r\n");
      out.write("  <!-- Subscribe section  -------------------------------------------------------------------------->\r\n");
      out.write("  <div class=\"w3-container w3-black w3-padding-32\">\r\n");
      out.write("    <h1>Subscribe</h1>\r\n");
      out.write("    <p>To get special offers and upate:</p>\r\n");
      out.write("    <p><input class=\"w3-input w3-border\" type=\"text\" placeholder=\"Enter e-mail\" style=\"width:100%\"></p>\r\n");
      out.write("    <button type=\"button\" class=\"w3-button w3-red w3-margin-bottom\">Subscribe</button>\r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- Subscribe section  -------------------------------------------------------------------------->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!-- Footer -------------------------------------------------------------------------------------->\r\n");
      out.write("  <footer class=\"w3-padding-64 w3-light-grey w3-small w3-center\" id=\"footer\">\r\n");
      out.write("    <div class=\"w3-row-padding\">\r\n");
      out.write("      <div class=\"w3-col s4\">\r\n");
      out.write("        <h4>Contact</h4>\r\n");
      out.write("        <p>Questions? Go ahead.</p>\r\n");
      out.write("        <form action=\"/action_page.php\" target=\"_blank\">\r\n");
      out.write("          <p><input class=\"w3-input w3-border\" type=\"text\" placeholder=\"Name\" name=\"Name\" required></p>\r\n");
      out.write("          <p><input class=\"w3-input w3-border\" type=\"text\" placeholder=\"Email\" name=\"Email\" required></p>\r\n");
      out.write("          <p><input class=\"w3-input w3-border\" type=\"text\" placeholder=\"Subject\" name=\"Subject\" required></p>\r\n");
      out.write("          <p><input class=\"w3-input w3-border\" type=\"text\" placeholder=\"Message\" name=\"Message\" required></p>\r\n");
      out.write("          <button type=\"submit\" class=\"w3-button w3-block w3-black\">Send</button>\r\n");
      out.write("        </form>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"w3-col s4\">\r\n");
      out.write("        <h4>About</h4>\r\n");
      out.write("        <p>Ketupat Sdn Bhd. is a company that produce Baju Melayu for all people regardless of their race. Every day, so many orders is received from customers of Ketupat Sdn Bhd. They faced a difficulty in keeping up with the ongoing orders, stock of products etc. The current way they manage their order is by using a manual way which is write on a logbook which consume a lot of times and mistake often occurs. They hope to have a new system that can help them handle the task. </p>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"w3-col s4 w3-justify\">\r\n");
      out.write("        <h4>Store</h4>\r\n");
      out.write("        <p><i class=\"fa fa-fw fa-map-marker\"></i> Ketupat Sdn Bhd.</p>\r\n");
      out.write("        <p><i class=\"fa fa-fw fa-phone\"></i> 0044123123</p>\r\n");
      out.write("        <p><i class=\"fa fa-fw fa-envelope\"></i> Ketupat@mail.com</p>\r\n");
      out.write("        <h4>We accept</h4>\r\n");
      out.write("        <p><i class=\"fa fa-fw fa-cc-amex\"></i> Paypal</p>\r\n");
      out.write("        <p><i class=\"fa fa-fw fa-credit-card\"></i> Credit Card</p>\r\n");
      out.write("        <br>\r\n");
      out.write("        <i class=\"fa fa-facebook-official w3-hover-opacity w3-large\"></i>\r\n");
      out.write("        <i class=\"fa fa-instagram w3-hover-opacity w3-large\"></i>\r\n");
      out.write("        <i class=\"fa fa-snapchat w3-hover-opacity w3-large\"></i>\r\n");
      out.write("        <i class=\"fa fa-pinterest-p w3-hover-opacity w3-large\"></i>\r\n");
      out.write("        <i class=\"fa fa-twitter w3-hover-opacity w3-large\"></i>\r\n");
      out.write("        <i class=\"fa fa-linkedin w3-hover-opacity w3-large\"></i>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </footer>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"w3-black w3-center w3-padding-24\">Powered by <a  title=\"Ketupat Sdn Bhd\" target=\"_blank\" class=\"w3-hover-opacity\">Ketupat Sdn Bhd</a></div>\r\n");
      out.write("\r\n");
      out.write("  <!-- Footer -------------------------------------------------------------------------------------->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!-- End page content -->\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Newsletter Modal -->\r\n");
      out.write("<div id=\"newsletter\" class=\"w3-modal\">\r\n");
      out.write("  <div class=\"w3-modal-content w3-animate-zoom\" style=\"padding:32px\">\r\n");
      out.write("    <div class=\"w3-container w3-white w3-center\">\r\n");
      out.write("      <i onclick=\"document.getElementById('newsletter').style.display='none'\" class=\"fa fa-remove w3-right w3-button w3-transparent w3-xxlarge\"></i>\r\n");
      out.write("      <h2 class=\"w3-wide\">NEWSLETTER</h2>\r\n");
      out.write("      <p>Join our mailing list to receive updates on new arrivals and special offers.</p>\r\n");
      out.write("      <p><input class=\"w3-input w3-border\" type=\"text\" placeholder=\"Enter e-mail\"></p>\r\n");
      out.write("      <button type=\"button\" class=\"w3-button w3-padding-large w3-red w3-margin-bottom\" onclick=\"document.getElementById('newsletter').style.display='none'\">Subscribe</button>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("// Accordion \r\n");
      out.write("function myAccFunc() {\r\n");
      out.write("  var x = document.getElementById(\"demoAcc\");\r\n");
      out.write("  if (x.className.indexOf(\"w3-show\") == -1) {\r\n");
      out.write("    x.className += \" w3-show\";\r\n");
      out.write("  } else {\r\n");
      out.write("    x.className = x.className.replace(\" w3-show\", \"\");\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// Click on the \"Jeans\" link on page load to open the accordion for demo purposes\r\n");
      out.write("document.getElementById(\"myBtn\").click();\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("// Open and close sidebar\r\n");
      out.write("function w3_open() {\r\n");
      out.write("  document.getElementById(\"mySidebar\").style.display = \"block\";\r\n");
      out.write("  document.getElementById(\"myOverlay\").style.display = \"block\";\r\n");
      out.write("}\r\n");
      out.write(" \r\n");
      out.write("function w3_close() {\r\n");
      out.write("  document.getElementById(\"mySidebar\").style.display = \"none\";\r\n");
      out.write("  document.getElementById(\"myOverlay\").style.display = \"none\";\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /adminViewReview.jsp(260,2) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${reviewList}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /adminViewReview.jsp(260,2) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("review");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t<tr>\r\n");
            out.write("\t\t\t\t<td>");
            if (_jspx_meth_c_005fout_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("</td>\r\n");
            out.write("\t\t\t\t<td>");
            if (_jspx_meth_c_005fout_005f1(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("</td>\r\n");
            out.write("\t\t\t\t<td>");
            if (_jspx_meth_c_005fout_005f2(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("</td>\r\n");
            out.write("\t\t\t\t<td>");
            if (_jspx_meth_c_005fout_005f3(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("</td>\r\n");
            out.write("\t\t\t\t<td>");
            if (_jspx_meth_c_005fout_005f4(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("</td>\r\n");
            out.write("\t\t\t\t<td>");
            if (_jspx_meth_c_005fout_005f5(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("</td>\r\n");
            out.write("\t\t\t\t<td>\r\n");
            out.write("\t\t\t\t\t<a href=\"UpdateReviewController?action=updater&review_id=");
            if (_jspx_meth_c_005fout_005f6(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\">Update</a>\r\n");
            out.write("\t\t\t\t\t<a href=\"deleteReviewController?action=delete&review_id=");
            if (_jspx_meth_c_005fout_005f7(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\">Delete</a>\r\n");
            out.write("\t\t\t\t</td>\r\n");
            out.write("\t\t\t</tr>\r\n");
            out.write("\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /adminViewReview.jsp(262,8) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${review.reviewID}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f1_reused = false;
    try {
      _jspx_th_c_005fout_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /adminViewReview.jsp(263,8) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${review.productName}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f1 = _jspx_th_c_005fout_005f1.doStartTag();
      if (_jspx_th_c_005fout_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
      _jspx_th_c_005fout_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f2 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f2_reused = false;
    try {
      _jspx_th_c_005fout_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /adminViewReview.jsp(264,8) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f2.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${review.reviewStar}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f2 = _jspx_th_c_005fout_005f2.doStartTag();
      if (_jspx_th_c_005fout_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f2);
      _jspx_th_c_005fout_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f3 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f3_reused = false;
    try {
      _jspx_th_c_005fout_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /adminViewReview.jsp(265,8) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f3.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${review.reviewText}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f3 = _jspx_th_c_005fout_005f3.doStartTag();
      if (_jspx_th_c_005fout_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f3);
      _jspx_th_c_005fout_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f4 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f4_reused = false;
    try {
      _jspx_th_c_005fout_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /adminViewReview.jsp(266,8) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f4.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${review.paymentDate}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f4 = _jspx_th_c_005fout_005f4.doStartTag();
      if (_jspx_th_c_005fout_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f4);
      _jspx_th_c_005fout_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f5 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f5_reused = false;
    try {
      _jspx_th_c_005fout_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /adminViewReview.jsp(267,8) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f5.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${review.customerEmail}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f5 = _jspx_th_c_005fout_005f5.doStartTag();
      if (_jspx_th_c_005fout_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f5);
      _jspx_th_c_005fout_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f5, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f6(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f6 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f6_reused = false;
    try {
      _jspx_th_c_005fout_005f6.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f6.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /adminViewReview.jsp(269,62) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f6.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${review.reviewID}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f6 = _jspx_th_c_005fout_005f6.doStartTag();
      if (_jspx_th_c_005fout_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f6);
      _jspx_th_c_005fout_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f6, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f7(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f7 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f7_reused = false;
    try {
      _jspx_th_c_005fout_005f7.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f7.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /adminViewReview.jsp(270,61) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f7.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${review.reviewID}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f7 = _jspx_th_c_005fout_005f7.doStartTag();
      if (_jspx_th_c_005fout_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f7);
      _jspx_th_c_005fout_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f7, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f7_reused);
    }
    return false;
  }
}
